"""
PDF report generator: produces a professional, branded PDF report
for a given meeting analysis using ReportLab.
"""

import io
import json
import logging
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# ── Brand colors ───────────────────────────────────────────────────────────────
INDIGO      = colors.HexColor("#6366F1")
INDIGO_DARK = colors.HexColor("#4338CA")
CYAN        = colors.HexColor("#22D3EE")
SLATE_900   = colors.HexColor("#0F172A")
SLATE_800   = colors.HexColor("#1E293B")
SLATE_600   = colors.HexColor("#475569")
SLATE_200   = colors.HexColor("#E2E8F0")
WHITE       = colors.white
EMERALD     = colors.HexColor("#10B981")
AMBER       = colors.HexColor("#F59E0B")


def _safe_json(raw: str) -> list:
    if not raw:
        return []
    try:
        val = json.loads(raw)
        return val if isinstance(val, list) else []
    except (json.JSONDecodeError, TypeError):
        return []


def _styles() -> dict:
    """Build and return a mapping of custom paragraph styles."""
    base = getSampleStyleSheet()

    s = {}

    s["title"] = ParagraphStyle(
        "ReportTitle",
        fontSize=26, leading=32,
        textColor=WHITE,
        fontName="Helvetica-Bold",
        spaceAfter=4,
    )
    s["subtitle"] = ParagraphStyle(
        "Subtitle",
        fontSize=11, leading=16,
        textColor=colors.HexColor("#94A3B8"),
        fontName="Helvetica",
        spaceAfter=0,
    )
    s["section"] = ParagraphStyle(
        "Section",
        fontSize=13, leading=18,
        textColor=INDIGO,
        fontName="Helvetica-Bold",
        spaceBefore=18, spaceAfter=6,
    )
    s["body"] = ParagraphStyle(
        "Body",
        fontSize=10, leading=15,
        textColor=SLATE_900,
        fontName="Helvetica",
        spaceAfter=4,
    )
    s["label"] = ParagraphStyle(
        "Label",
        fontSize=9, leading=13,
        textColor=SLATE_600,
        fontName="Helvetica-Oblique",
    )
    s["kpi_value"] = ParagraphStyle(
        "KpiValue",
        fontSize=22, leading=28,
        textColor=INDIGO,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
    )
    s["kpi_label"] = ParagraphStyle(
        "KpiLabel",
        fontSize=9, leading=12,
        textColor=SLATE_600,
        fontName="Helvetica",
        alignment=TA_CENTER,
    )
    return s


class _HeaderFooterTemplate(PageTemplate):
    """Custom page template with a branded header and footer."""

    def __init__(self, page_size, meeting_name: str):
        w, h = page_size
        self.meeting_name = meeting_name
        frame = Frame(
            1.5 * cm, 2.5 * cm,
            w - 3 * cm, h - 5 * cm,
            id="main",
        )
        super().__init__("main", [frame])

    def beforeDrawPage(self, canvas, doc):
        w, h = doc.pagesize

        # Header background bar
        canvas.setFillColor(SLATE_900)
        canvas.rect(0, h - 55, w, 55, fill=True, stroke=False)

        # Accent stripe
        canvas.setFillColor(INDIGO)
        canvas.rect(0, h - 58, w, 3, fill=True, stroke=False)

        # Header text
        canvas.setFillColor(WHITE)
        canvas.setFont("Helvetica-Bold", 13)
        canvas.drawString(1.5 * cm, h - 36, "AI Meeting Intelligence")

        canvas.setFillColor(colors.HexColor("#94A3B8"))
        canvas.setFont("Helvetica", 9)
        canvas.drawString(1.5 * cm, h - 50, self.meeting_name[:70])

        # Page number (top-right)
        canvas.setFillColor(colors.HexColor("#94A3B8"))
        canvas.setFont("Helvetica", 9)
        canvas.drawRightString(w - 1.5 * cm, h - 42, f"Page {doc.page}")

        # Footer
        canvas.setFillColor(SLATE_200)
        canvas.rect(0, 0, w, 38, fill=True, stroke=False)
        canvas.setFillColor(SLATE_600)
        canvas.setFont("Helvetica", 8)
        canvas.drawString(
            1.5 * cm, 14,
            f"Generated by AI Meeting Intelligence  |  {datetime.now().strftime('%B %d, %Y  %H:%M')}",
        )
        canvas.drawRightString(w - 1.5 * cm, 14, "Confidential")


def _kpi_table(metrics: dict, styles: dict) -> Table:
    """Build a 4-column KPI snapshot table."""
    labels = ["Meetings", "Action Items", "Decisions", "Deadlines"]
    values = [
        str(metrics.get("total_meetings", 0)),
        str(metrics.get("total_tasks", 0)),
        str(metrics.get("total_decisions", 0)),
        str(metrics.get("total_deadlines", 0)),
    ]

    header_row = [Paragraph(v, styles["kpi_value"]) for v in values]
    label_row  = [Paragraph(l, styles["kpi_label"]) for l in labels]

    tbl = Table([header_row, label_row], colWidths=[3.8 * cm] * 4)
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX",        (0, 0), (-1, -1), 0.5, SLATE_200),
        ("INNERGRID",  (0, 0), (-1, -1), 0.5, SLATE_200),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#F8FAFC")]),
    ]))
    return tbl


def _section_table(rows: list[list[str]], col_headers: list[str]) -> Table:
    """Generic striped data table for action items, decisions, deadlines."""
    header = [Paragraph(h, ParagraphStyle(
        "TH", fontSize=9, fontName="Helvetica-Bold",
        textColor=WHITE, alignment=TA_LEFT
    )) for h in col_headers]

    body_rows = []
    for row in rows:
        body_rows.append([
            Paragraph(str(cell), ParagraphStyle(
                "TD", fontSize=9, fontName="Helvetica",
                textColor=SLATE_900, leading=13
            ))
            for cell in row
        ])

    all_rows = [header] + body_rows

    col_width = 15.5 * cm / len(col_headers)
    tbl = Table(all_rows, colWidths=[col_width] * len(col_headers))

    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INDIGO),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, colors.HexColor("#F8FAFC")]),
        ("BOX",       (0, 0), (-1, -1), 0.4, SLATE_200),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, SLATE_200),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ])
    tbl.setStyle(style)
    return tbl


def generate_pdf_report(meeting: dict, metrics: dict) -> bytes:
    """
    Generate a full PDF report for a single meeting.

    Args:
        meeting: meeting dict from the database
        metrics: aggregated KPI dict from analytics.compute_summary_metrics

    Returns:
        Raw PDF bytes suitable for a Streamlit download button.
    """
    buffer = io.BytesIO()
    doc = BaseDocTemplate(buffer, pagesize=A4)
    styles = _styles()

    meeting_name = meeting.get("meeting_name", "Meeting Report")
    upload_date  = meeting.get("upload_date", "")[:10]

    # Register page template
    template = _HeaderFooterTemplate(A4, meeting_name)
    doc.addPageTemplates([template])

    story = []

    # ── Cover / title block ───────────────────────────────────────────────────
    story.append(Spacer(1, 0.8 * cm))
    story.append(Paragraph(meeting_name, styles["title"]))
    story.append(Paragraph(f"Meeting Report  ·  {upload_date}", styles["subtitle"]))
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=INDIGO))
    story.append(Spacer(1, 0.4 * cm))

    # ── KPI snapshot ──────────────────────────────────────────────────────────
    story.append(Paragraph("Analytics Snapshot", styles["section"]))
    story.append(_kpi_table(metrics, styles))
    story.append(Spacer(1, 0.5 * cm))

    # ── Summary ───────────────────────────────────────────────────────────────
    summary = meeting.get("summary", "No summary available.")
    story.append(Paragraph("Meeting Summary", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=SLATE_200))
    story.append(Spacer(1, 0.2 * cm))
    for para in summary.split("\n"):
        if para.strip():
            story.append(Paragraph(para.strip(), styles["body"]))
    story.append(Spacer(1, 0.4 * cm))

    # ── Action items ──────────────────────────────────────────────────────────
    action_items = _safe_json(meeting.get("action_items", "[]"))
    story.append(Paragraph("Action Items", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=SLATE_200))
    story.append(Spacer(1, 0.2 * cm))
    if action_items:
        rows = [[item.get("person", "-"), item.get("task", "-")] for item in action_items]
        story.append(_section_table(rows, ["Assignee", "Task"]))
    else:
        story.append(Paragraph("No action items detected.", styles["label"]))
    story.append(Spacer(1, 0.4 * cm))

    # ── Decisions ─────────────────────────────────────────────────────────────
    decisions = _safe_json(meeting.get("decisions", "[]"))
    story.append(Paragraph("Decisions Made", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=SLATE_200))
    story.append(Spacer(1, 0.2 * cm))
    if decisions:
        rows = [[d.get("decision", "-"), d.get("context", "-")[:120]] for d in decisions]
        story.append(_section_table(rows, ["Decision", "Context"]))
    else:
        story.append(Paragraph("No decisions detected.", styles["label"]))
    story.append(Spacer(1, 0.4 * cm))

    # ── Deadlines ─────────────────────────────────────────────────────────────
    deadlines = _safe_json(meeting.get("deadlines", "[]"))
    story.append(Paragraph("Deadlines & Due Dates", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=SLATE_200))
    story.append(Spacer(1, 0.2 * cm))
    if deadlines:
        rows = [[d.get("date", "-"), d.get("deadline", "-")] for d in deadlines]
        story.append(_section_table(rows, ["Date", "Deadline Statement"]))
    else:
        story.append(Paragraph("No deadlines detected.", styles["label"]))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
